name: Test Workflow
on:
  push:
    branches-ignore:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node 12.7
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12.7"

      - name: node_modules cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-nm-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Run Validate
        run: |
          yarn validate
